server:
  port: 9000
  error:
    whitelabel:
      enabled: true

spring:
  datasource:
    url: ${DATABASE_CONNECTION_URL}
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true

  h2:
    console:
      enabled: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      SQL: debug