spring:
  application:
    name: todo-family

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    default-property-inclusion: non_null
    deserialization:
      fail-on-null-for-primitives: true

  profiles:
    active: ${SCOPE:dev}

api:
  app:
    jwtCookieName: token
    jwtSecret: ${SECRET:localSecret}
    jwtExpirationMs: 86400000